export default [
    { name: "Alice Johnson", id: 1, email: "alice.johnson@example.com", password: "pass1" },
    { name: "Benjamin Smith", id: 2, email: "ben.smith@example.com", password: "pass2" },
    { name: "Carla Martinez", id: 3, email: "carla.martinez@example.com", password: "pass3" },
    { name: "David Lee", id: 4, email: "david.lee@example.com", password: "pass4" },
    { name: "Emma Brown", id: 5, email: "emma.brown@example.com", password: "pass5" },
    { name: "Felix Wilson", id: 6, email: "felix.wilson@example.com", password: "pass6" },
    { name: "Grace Kim", id: 7, email: "grace.kim@example.com", password: "pass7" },
    { name: "Henry Clark", id: 8, email: "henry.clark@example.com", password: "pass8" },
    { name: "Isabella Turner", id: 9, email: "isabella.turner@example.com", password: "pass9" },
    { name: "Jackie Evans", id: 10, email: "jackie.evans@example.com", password: "pass10" },
    { name: "Kevin Walker", id: 11, email: "kevin.walker@example.com", password: "pass11" },
    { name: "Laura Scott", id: 12, email: "laura.scott@example.com", password: "pass12" },
    { name: "Michael Adams", id: 13, email: "michael.adams@example.com", password: "pass13" },
    { name: "Natalie Baker", id: 14, email: "natalie.baker@example.com", password: "pass14" },
    { name: "Oliver Hill", id: 15, email: "oliver.hill@example.com", password: "pass15" },
    { name: "Penelope Reed", id: 16, email: "penelope.reed@example.com", password: "pass16" },
    { name: "Quentin Foster", id: 17, email: "quentin.foster@example.com", password: "pass17" },
    { name: "Rachel Gray", id: 18, email: "rachel.gray@example.com", password: "pass18" },
];
